### PR TITLE
fix CJK character cannot display CORRECTLY

### PR DESCRIPTION
**Pull request by dennischancs**
use `io.StringIO` in linux instead of `contextlib.ExitStack`

### CODE REVIEW

**Comment by anntzer** [comment]
Please clarify the context where this is necessary.

**Comment by dennischancs** [comment]
> Please clarify the context where this is necessary.
This is a comparison of before and after:

**Comment by anntzer** [comment]
Thanks.  I'll have a look, though before a week or two.

**Comment by anntzer** [comment]
I cannot repro your problem; things just work fine for me as of master:
zw

**Comment by anntzer** [comment]
Closing as non-reproducible, and also because there are far too many changes unrelated to the reported CJK problem anyways.

**Pull request closed without merging**
