### PR TITLE
Clarify installation instructions.

### PR DESCRIPTION
**Pull request by anntzer**
attn @twocs: how does that look to you?

### CODE REVIEW

**Comment by imatlab-helper** [comment]
Just a note, some of these steps are Windows specific. In Linux, there is no need to copy the plotly offline JS file anywhere, as it gets installed in ```~/.plotly/plotlyjs``` after calling ```getplotlyoffline```. Furhter, no plotly credentials are necessary to get this to work in Linux.

**Comment by imatlab-helper** [comment]
Looking at this more closely, it might seem like ```signin``` works even without credentials in Linux. Was the goal here to have a unified set of instructions such that they work on all platforms?

Separately, I'm not too pleased with the idea of ```signin``` being a plotly api command. It's not package specific at all. The same goes for a lot of functions in that package.

**Comment by twocs** [comment]
I think signin works without credentials in Linux only because the `import plotly` python statement creates the credentials (behind the scenes). You can see this occurring by deleting the credentials, then in a Python console doing `import plotly`. So it's not working without credentials in Linux, the credentials just conveniently appear there from an unrelated step.

In the instructions, where it says, "copy the required JavaScript files", that is being done by `getplotlyoffline('https://cdn.plot.ly/plotly-latest.min.js');` in both Windows and Linux. There's no manual copying.

**Comment by imatlab-helper** [comment]
Fair enough, that makes sense. I suppose it's better to have them explicit. Thanks.

**Comment by anntzer** [comment]
I'd rather keep the instructions the same for all OSes if possible, even at the expense of slight redundancy in some cases.
Complaints about the plotly API should go, well, to plotly :-)

**Pull request merged**
